# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d356ac975462ccce7d315e061eec1de375a41ebf809f8a54faa45b074c90c94b4565d1407fde0644dc0cd4e43d6365dbd41d8c9dc4d6585a38455c00e7fef052

test:
  secret_key_base: 9ae2edd8843815dea434184718fcc05e1af9b29fc6e85b894889d054cc6a679245536728b129696f4745961637e3b6e6b6780224b90dd8ff3f0bc819ba0e8209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
